# Generated by Django 4.2.6 on 2023-11-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(default='', max_length=32)),
                ('produto', models.ManyToManyField(related_name='categorias', to='ecommerce.produto')),
            ],
        ),
    ]
