# Generated by Django 4.2.6 on 2023-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_user_adm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho_g',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho_gg',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho_m',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho_p',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
