# Generated by Django 4.2.6 on 2023-11-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_cupom_nome_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='porcentagem',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
