# Generated by Django 4.2.6 on 2023-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cupom_porcentagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='porcentagem',
            field=models.IntegerField(null=True),
        ),
    ]
