# Generated by Django 4.2.6 on 2023-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_itempedido_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
