# Generated by Django 4.2.6 on 2023-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_produto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
