# Generated by Django 4.2.6 on 2023-11-06 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_pedido_cupom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='compras',
            field=models.ManyToManyField(blank=True, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
