# Generated by Django 4.2.6 on 2023-11-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_produto_compras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='compras',
            new_name='compradores',
        ),
    ]
