# Generated by Django 4.2.6 on 2023-11-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_pedido_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='novo_valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
