# Generated by Django 4.2.6 on 2023-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='estrelas',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
