# Generated by Django 4.2.6 on 2023-11-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_comment_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='estrelas',
            field=models.IntegerField(null=True),
        ),
    ]
