# Generated by Django 4.2.6 on 2023-11-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_comment_estrelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
