# Generated by Django 4.2.6 on 2023-11-07 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_endereco_bairro_alter_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='ecommerce.pedido'),
        ),
    ]
