from django.contrib import admin
from .models import User, Produto, ItemPedido, Pedido, Endereco, Categoria

class ProdutoInline(admin.StackedInline):  # or admin.StackedInline if you prefer a different layout
    model = Produto.categorias.through  # The through model autogenerated by the ManyToManyField
    extra = 1  # Number of extra forms to display

class CategoriaAdmin(admin.ModelAdmin):
    inlines = [ProdutoInline,]
    exclude = ['produto',]

# Register your models here.

admin.site.register(User)
admin.site.register(Pedido)
admin.site.register(Produto)
admin.site.register(Endereco)
admin.site.register(ItemPedido)
admin.site.register(Categoria, CategoriaAdmin)